# Generated by Django 4.2.7 on 2025-10-17 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, в котором необходимо выполнять привычку', max_length=200, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время, когда необходимо выполнять привычку', verbose_name='Время')),
                ('action', models.CharField(help_text='Действие, которое представляет собой привычка', max_length=200, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Привычка, которую можно привязать к выполнению полезной привычки', verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Периодичность выполнения привычки для напоминания в днях', verbose_name='Периодичность (дни)')),
                ('reward', models.CharField(blank=True, help_text='Чем пользователь должен себя вознаградить после выполнения', max_length=200, null=True, verbose_name='Вознаграждение')),
                ('estimated_time', models.PositiveIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки', verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(default=False, help_text='Привычки можно публиковать в общий доступ', verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, которая связана с полезной привычкой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время выполнения')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Выполнено')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Лог привычки',
                'verbose_name_plural': 'Логи привычек',
                'ordering': ['-completed_at'],
            },
        ),
    ]
